torre_crud/urls.py
from django.urls import path
from . import views

app_name = 'torre_crud'

urlpatterns = [
    path('', views.Inicio.as_view(), name='inicio'),

    # URLs para Deportes
    path('deportes/', views.DeportesListView.as_view(), name='deportes-list'),
    path('deportes/crear/', views.DeportesCreateView.as_view(), name='deportes-create'),
    path('deportes/<int:pk>/editar/', views.DeportesUpdateView.as_view(), name='deportes-update'),
    path('deportes/<int:pk>/eliminar/', views.DeportesDeleteView.as_view(), name='deportes-delete'),

    # URLs para Instalaciones
    path('instalaciones/', views.InstalacionesListView.as_view(), name='instalaciones-list'),
    path('instalaciones/crear/', views.InstalacionesCreateView.as_view(), name='instalaciones-create'),
    path('instalaciones/<int:pk>/editar/', views.InstalacionesUpdateView.as_view(), name='instalaciones-update'),
    path('instalaciones/<int:pk>/eliminar/', views.InstalacionesDeleteView.as_view(), name='instalaciones-delete'),

    # URLs para Equipos
    path('equipos/', views.EquiposListView.as_view(), name='equipos-list'),
    path('equipos/crear/', views.EquiposCreateView.as_view(), name='equipos-create'),
    path('equipos/<int:pk>/editar/', views.EquiposUpdateView.as_view(), name='equipos-update'),
    path('equipos/<int:pk>/eliminar/', views.EquiposDeleteView.as_view(), name='equipos-delete'),
    path('equipos/<int:pk>/', views.EquipoDetailView.as_view(), name='equipo-detail'),
    path('equipos/<int:pk>/jugadores', views.EquipoJugadorCreate.as_view(), name='equipo-jugador-create'),

    # URLs para Jugadores
    path('jugadores/', views.JugadorListView.as_view(), name='jugadores-list'),
    path('jugadores/crear/', views.JugadorCreateView.as_view(), name='jugadores-create'),
    path('jugadores/<int:pk>/editar/', views.JugadorUpdateView.as_view(), name='jugadores-update'),
    path('jugadores/<int:pk>/eliminar/', views.JugadorDeleteView.as_view(), name='jugadores-delete'),
    path('jugadores/<int:pk>/', views.JugadorDetailView.as_view(), name='jugador-detail'),

    # URLs para Partidos
    path('partidos/', views.PartidoListView.as_view(), name='partidos-list'),
    path('partidos/crear/', views.PartidoCreateView.as_view(), name='partidos-create'),
    path('partidos/<int:pk>/editar/', views.PartidoUpdateView.as_view(), name='partidos-update'),
    path('partidos/<int:pk>/eliminar/', views.PartidoDeleteView.as_view(), name='partidos-delete'),
    path('partidos/<int:pk>/', views.PartidoDetailView.as_view(), name='partidos-detail'),
]

torre_sport_proyect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('torre_crud.urls', namespace='default')),  
    path('torreCrud/', include('torre_crud.urls', namespace='torre_crud')),
]

torre_crud/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Deportes(models.Model):
    id_deporte = models.AutoField(primary_key=True)
    nombre = models.CharField(unique=True, max_length=20)

    class Meta:
        managed = False
        verbose_name = "Deporte"
        verbose_name_plural = "Deportes"
        db_table = 'deportes'
    
    def __str__(self):
        return self.nombre


class Equipos(models.Model):
    id_equipo = models.AutoField(primary_key=True)
    nombre = models.CharField(unique=True, max_length=20)
    id_deporte = models.ForeignKey(Deportes, models.DO_NOTHING, db_column='id_deporte', default = 0)
    equipacion_principal = models.CharField(max_length=100)
    equipacion_suplente = models.CharField(max_length=100)
    contacto = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()

    class Meta:
        managed = False
        verbose_name = "Equipo"
        verbose_name_plural = "Equipos"
        db_table = 'equipos'
    
    def __str__(self):
        return self.nombre


class Instalaciones(models.Model):
    id_instalacion = models.AutoField(primary_key=True)
    nombre = models.CharField(unique=True, max_length=20)
    direccion = models.CharField(max_length=100)
    iluminacion = models.BooleanField(default=False)
    cubierta = models.BooleanField(default=False)

    class Meta:
        managed = False
        verbose_name = "Instalación"
        verbose_name_plural = "Instalaciones"
        db_table = 'instalaciones'

    def __str__(self):
        return self.nombre



class Jugadores(models.Model):
    id_jugador = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20)
    apellido1 = models.CharField(max_length=20)
    apellido2 = models.CharField(max_length=20, blank=True, null=True)
    id_equipo = models.ForeignKey(Equipos, models.DO_NOTHING, db_column='id_equipo', default = 0)
    dorsal = models.IntegerField()
    fecha_nacimiento = models.DateField()
    altura = models.DecimalField(max_digits=3, decimal_places=2, validators=[MinValueValidator(0)])
    peso = models.IntegerField(validators=[MinValueValidator(0)])
    telefono = models.CharField(max_length=15)

    class Meta:
        managed = False
        db_table = 'jugadores'
        unique_together = (('id_equipo', 'dorsal'),)
        verbose_name = "Jugador"
        verbose_name_plural = "Jugadores"
        


class Partidos(models.Model):
    id_partido = models.AutoField(primary_key=True)
    id_deporte = models.ForeignKey(Deportes, models.DO_NOTHING, db_column='id_deporte')
    fecha_hora = models.DateTimeField()
    id_instalacion = models.ForeignKey(Instalaciones, models.DO_NOTHING, db_column='id_instalacion', blank=True, null=True)
    id_local = models.ForeignKey(Equipos, models.DO_NOTHING, db_column='id_local')
    id_visitante = models.ForeignKey(Equipos, models.DO_NOTHING, db_column='id_visitante', related_name='partidos_id_visitante_set')
    puntos_local = models.IntegerField(blank=True, null=True, default=0, validators=[MinValueValidator(0)])
    puntos_visitante = models.IntegerField(blank=True, null=True, default=0, validators=[MinValueValidator(0)])
    observaciones = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'partidos'
        verbose_name = "Partido"
        verbose_name_plural = "Partidos"

torre_crud/forms.py
from django import forms
from . import models

class DeporteForm(forms.ModelForm):
    class Meta:
        model = models.Deportes
        exclude = ['id_deporte']

class InstalacionForm(forms.ModelForm):
    class Meta:
        model = models.Instalaciones
        exclude = ['id_instalacion']

class EquipoForm(forms.ModelForm):
    class Meta:
        model = models.Equipos
        exclude = ['id_equipo']

class JugadorForm(forms.ModelForm):
    class Meta:
        model = models.Jugadores
        exclude = ['id_jugador']

class PartidoForm(forms.ModelForm):
    class Meta:
        model = models.Partidos
        exclude = ['id_partido']
        widgets = {
            'fecha_hora': forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'observaciones': forms.Textarea(attrs={'rows': 4}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        id_local = cleaned_data.get('id_local')
        id_visitante = cleaned_data.get('id_visitante')

        # Verificar si el mismo equipo ha sido seleccionado como local y visitante
        if id_local == id_visitante:
            raise forms.ValidationError("El mismo equipo no puede ser seleccionado como local y visitante")

        return cleaned_data

torre_crud/views.py
from datetime import datetime
from django.urls import reverse_lazy
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from . import models
from .forms import DeporteForm, InstalacionForm, EquipoForm, JugadorForm, PartidoForm

class Inicio(generic.ListView):
    template_name = 'inicio.html'  
    context_object_name = 'contexto'  

    def get_queryset(self):
        return models.Partidos.objects.none()  

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Página de inicio'
        """ contexto['menu_opciones'] = ['deportes', 'instalaciones', 'equipos', 'jugadores', 'partidos']
        contexto['imagen_deporte_url'] = 'URL_DE_LA_IMAGEN' """
        contexto['ultimos_partidos'] = models.Partidos.objects.filter(fecha_hora__lt=datetime.now()).order_by('-fecha_hora')[:5]
        contexto['proximos_partidos'] = models.Partidos.objects.filter(fecha_hora__gte=datetime.now()).order_by('fecha_hora')[:5]
        return contexto

""" Deportes """

class DeportesListView(generic.ListView):
    template_name = 'deportes_list.html'
    context_object_name = 'deportes'

    def get_queryset(self):
        return models.Deportes.objects.all()

class DeportesCreateView(generic.CreateView):
    model = models.Deportes
    form_class = DeporteForm
    template_name = 'deportes_create.html'
    success_url = reverse_lazy('torre_crud:deportes-list') 

class DeportesDeleteView(generic.DeleteView):
    model = models.Deportes
    template_name = 'deportes_confirm_delete.html'
    success_url = reverse_lazy('torre_crud:deportes-list')

class DeportesUpdateView(generic.UpdateView):
    model = models.Deportes
    form_class = DeporteForm
    template_name = 'deportes_update.html'
    success_url = reverse_lazy('torre_crud:deportes-list')

""" Instalaciones """

class InstalacionesListView(generic.ListView):
    template_name = 'instalaciones_list.html'
    context_object_name = 'instalaciones'

    def get_queryset(self):
        return models.Instalaciones.objects.all()

class InstalacionesCreateView(generic.CreateView):
    model = models.Instalaciones
    form_class = InstalacionForm
    template_name = 'instalaciones_create.html'
    success_url = reverse_lazy('torre_crud:instalaciones-list')

class InstalacionesDeleteView(generic.DeleteView):
    model = models.Instalaciones
    template_name = 'instalaciones_delete.html'
    success_url = reverse_lazy('torre_crud:instalaciones-list')

class InstalacionesUpdateView(generic.UpdateView):
    model = models.Instalaciones
    form_class = InstalacionForm
    template_name = 'instalaciones_update.html'
    success_url = reverse_lazy('torre_crud:instalaciones-list')

""" Equipo """

class EquiposListView(generic.ListView):
    template_name = 'equipos_list.html'
    context_object_name = 'equipos_list'

    def get_queryset(self):
        return models.Equipos.objects.all()

class EquiposCreateView(generic.CreateView):
    model = models.Equipos
    form_class = EquipoForm
    template_name = 'equipo_create.html'
    success_url = reverse_lazy('torre_crud:equipos-list')

class EquiposDeleteView(generic.DeleteView):
    model = models.Equipos
    template_name = 'equipo_confirm_delete.html'
    success_url = reverse_lazy('torre_crud:equipos-list')

class EquiposUpdateView(generic.UpdateView):
    model = models.Equipos
    form_class = EquipoForm
    template_name = 'equipo_update.html'
    success_url = reverse_lazy('torre_crud:equipos-list')

class EquipoDetailView(generic.DetailView):
    model = models.Equipos
    template_name = 'equipo_detail.html'
    context_object_name = 'equipo'

    def get_queryset(self):
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        equipo = self.get_object()
        jugadores = models.Jugadores.objects.filter(id_equipo=equipo)
        contexto['jugadores'] = jugadores
        return contexto
    

class EquipoJugadorCreate(generic.CreateView):
    model = models.Jugadores
    form_class = JugadorForm
    template_name = 'equipo_jugador_create.html'
    success_url = reverse_lazy('torre_crud:equipos-list')  # Esta es la URL a la que se redirigirá después de crear el jugador

    def get_initial(self):
        initial = super().get_initial()
        equipo_id = self.kwargs.get('pk')
        equipo = models.Equipos.objects.get(pk=equipo_id)
        initial['equipo'] = equipo
        return initial

""" Jugador """

class JugadorListView(generic.ListView):
    model = models.Jugadores
    template_name = 'jugadores_list.html'
    context_object_name = 'jugadores'
    

class JugadorCreateView(generic.CreateView):
    model = models.Jugadores
    form_class = JugadorForm
    success_url = reverse_lazy('torre_crud:jugadores-list') 
    template_name = 'jugador_create.html'

class JugadorUpdateView(generic.UpdateView):
    model = models.Jugadores
    form_class = JugadorForm
    success_url = reverse_lazy('torre_crud:jugadores-list') 
    template_name = 'jugador_update.html'

class JugadorDetailView(generic.DetailView):
    model = models.Jugadores
    template_name = 'jugador_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        jugador = self.get_object()
        context['equipo'] = jugador.id_equipo.nombre
        context['elJugador'] = jugador
        return context

class JugadorDeleteView(generic.DeleteView):
    model = models.Jugadores
    success_url = reverse_lazy('torre_crud:jugadores-list')  
    template_name = 'jugador_confirm_delete.html'

""" Partidos """

class PartidoListView(generic.ListView):
    model = models.Partidos
    template_name = 'partido_list.html'
    context_object_name = 'partidos'
    ordering = ['-fecha_hora']

class PartidoCreateView(generic.CreateView):
    model = models.Partidos
    form_class = PartidoForm
    success_url = reverse_lazy('torre_crud:partidos-list') 
    template_name = 'partido_create.html'

class PartidoUpdateView(generic.UpdateView):
    model = models.Partidos
    form_class = PartidoForm
    success_url = reverse_lazy('torre_crud:partidos-list') 
    template_name = 'partido_update.html'

class PartidoDetailView(generic.DetailView):
    model = models.Partidos
    template_name = 'partido_detail.html'
    context_object_name = 'partido'

class PartidoDeleteView(generic.DeleteView):
    model = models.Partidos
    success_url = reverse_lazy('torre_crud:partidos-list')
    template_name = 'partido_confirm_delete.html'

torre_crud/templates/deportes_create.html
{% extends 'base.html' %}

{% block title %}
<title>Añadir Deporte - {{ block.super }}</title>
{% endblock %}
{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}
{% block cuerpo %}
<div class="container mt-5">
    <h1>Añadir Deporte</h1>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            <div class="invalid-feedback">
                {{ form.nombre.errors }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/deportes_delete.html
{% extends 'base.html' %}

{% block title %}<title>Eliminar Deporte - {{ block.super }}</title>{% endblock %}
{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}
{% block cuerpo %}
<div class="container mt-5">
    <h1>Eliminar Deporte</h1>
    <p>¿Estás seguro de que deseas eliminar este deporte?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/deportes_list.html
{% extends 'base.html' %}

{% block title %}
<title>Lista de Deportes</title>
{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Lista de Deportes</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Acciones</th> <!-- Nueva columna para acciones -->
                </tr>
            </thead>
            <tbody>
                {% for deporte in deportes %}
                    <tr>
                        <td>{{ deporte.id_deporte }}</td>
                        <td>{{ deporte.nombre }}</td>
                        <td>
                            <a href="{% url 'torre_crud:deportes-update' deporte.id_deporte %}" class="btn btn-primary">Editar</a>
                            <form action="{% url 'torre_crud:deportes-delete' deporte.id_deporte %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                        </td>
                        {% empty %}
                        <td>No hay datos</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{% url 'torre_crud:deportes-create' %}" class="btn btn-success">Crear Deporte</a> <!-- Botón para crear un nuevo deporte -->
</div>
{% endblock %}

torre_crud/templates/deportes_update.html
{% extends 'base.html' %}

{% block title %}<title>Modificar Deporte - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Modificar Deporte</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/equipo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}<title>Eliminar Equipo - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Eliminar Equipo</h1>
    <p>¿Estás seguro de que deseas eliminar este equipo?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/equipo_create.html
{% extends 'base.html' %}

{% block title %}<title>Añadir Equipo - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Añadir Equipo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/equipo_detail.html
{% extends 'base.html' %}

{% block title %}<title>Detalle del Equipo - {{ equipo.nombre }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Detalle del Equipo - {{ equipo.nombre }}</h1>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Deporte</th>
                <th>Equipación Principal</th>
                <th>Equipación Suplente</th>
                <th>Contacto</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ equipo.id_equipo }}</td>
                <td>{{ equipo.nombre }}</td>
                <td>{{ equipo.id_deporte.nombre }}</td>
                <td>{{ equipo.contacto }}</td>
                <td>{{ equipo.equipacion_principal }}</td>
                <td>{{ equipo.equipacion_suplente }}</td>
                <td>{{ equipo.telefono }}</td>
                <td>{{ equipo.email }}</td>
            </tr>
        </tbody>
    </table>

    <h2>Jugadores</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Dorsal</th>
                <th>Nombre</th>
                <th>Apellidos</th>
            </tr>
        </thead>
        <tbody>
            {% for jugador in jugadores  %}
                <tr>
                    <td>{{ jugador.dorsal }}</td>
                    <td>{{ jugador.nombre }}</td>
                    <td>{{ jugador.apellido1 }} {{ jugador.apellido2 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'torre_crud:equipo-jugador-create' equipo.pk %}" class="btn btn-primary">Añadir Nuevo Jugador</a>
</div>
{% endblock %}

torre_crud/templates/equipo_update.html
{% extends 'base.html' %}

{% block title %}<title>Modificar Equipo - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Modificar Equipo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Página de Inicio</title>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>{{ titulo }}</h1>
    
    <!-- Menú -->
    {% comment %} <nav class="nav">
        {% for opcion in menu_opciones %}
            <a class="nav-link" href="{% url 'torre_crud:'|add:opcion|lower|add:'-list' %}">{{ opcion|title }}</a>
        {% endfor %}
    </nav> {% endcomment %}
    
    <!-- Imagen de deporte -->
    <img src="{% static 'img/futbolImg.jpg' %}" alt="Imagen de Deporte" class="img-fluid my-4">
    
    
    <div class="row">
        <!-- Listado de últimos partidos jugados -->
        <div class="col-md-6">
            <h2>Últimos partidos jugados</h2>
            <ul class="list-group">
                {% for partido in ultimos_partidos %}
                    <li class="list-group-item">{{ partido.fecha_hora|date:"d/m/Y H:i" }} - {{ partido.id_local }} VS {{ partido.id_visitante }}</li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- Listado de próximos partidos por jugar -->
        <div class="col-md-6">
            <h2>Próximos partidos por jugar</h2>
            <ul class="list-group">
                {% for partido in proximos_partidos %}
                    <li class="list-group-item">{{ partido.fecha_hora|date:"d/m/Y H:i" }} - {{ partido.id_local }} VS {{ partido.id_visitante }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

torre_crud/templates/jugador_create.html
{% extends 'base.html' %}

{% block title %}<title>Añadir Jugador - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Añadir Jugador</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/jugador_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>Detalle del Jugador - {{ elJugador.nombre }} {{ elJugador.apellido1 }} - {{ block.super }}</title>
{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Detalle del Jugador - {{ elJugador.nombre }} {{ elJugador.apellido1 }}</h1>
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Equipo</th>
                        <th>Dorsal</th>
                        <th>Fecha de Nacimiento</th>
                        <th>Altura</th>
                        <th>Peso</th>
                        <th>Teléfono</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        
                        <td>{{ elJugador.id_jugador }}</td>
                        <td>{{ elJugador.nombre }}</td>
                        <td>{{ elJugador.apellido1 }} {{ elJugador.apellido2 }}</td>
                        <td>{{ equipo }}</td>
                        <td>{{ elJugador.dorsal }}</td>
                        <td>{{ elJugador.fecha_nacimiento }}</td>
                        <td>{{ elJugador.altura }} m</td> 
                        <td>{{ elJugador.peso }} kg</td>
                        <td>{{ elJugador.telefono }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

torre_crud/templates/jugador_update.html
{% extends 'base.html' %}

{% block title %}<title>Modificar Jugador - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Modificar Jugador</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

torre_crud/templates/partido_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Listado de Partidos</title>
{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Listado de Partidos</h1>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Fecha y Hora</th>
                <th>Deporte</th>
                <th>Local</th>
                <th>Visitante</th>
                <th>Puntos Local</th>
                <th>Puntos Visitante</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for partido in partidos %}
                <tr>
                    <td>{{ partido.fecha_hora }}</td>
                    <td>{{ partido.id_deporte }}</td>
                    <td>{{ partido.id_local }}</td>
                    <td>{{ partido.id_visitante }}</td>
                    <td>{{ partido.puntos_local }}</td>
                    <td>{{ partido.puntos_visitante }}</td>
                    <td>
                        <a href="{% url 'torre_crud:partidos-detail' partido.id_partido %}" class="btn btn-info btn-sm">Detalle</a>
                        <a href="{% url 'torre_crud:partidos-update' partido.id_partido %}" class="btn btn-warning btn-sm">Modificar</a>
                        <a href="{% url 'torre_crud:partidos-delete' partido.id_partido %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                    {% empty %}
                    <td>No hay datos</td>
                </tr>
                
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'torre_crud:partidos-create' %}" class="btn btn-primary">Añadir Partido</a>
</div>
{% endblock %}

torre_crud/templates/partido_update.html
{% extends 'base.html' %}

{% block title %}<title>Modificar Partido - {{ block.super }}</title>{% endblock %}

{% block btn %}
<a class="btn btn-primary" href="{% url 'torre_crud:inicio' %}">Inicio</a>
{% endblock %}

{% block cuerpo %}
<div class="container mt-5">
    <h1>Modificar Partido</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</div>
{% endblock %}